foreground   #cfcfce
background   #05030B
cursor       #cfcfce

color0       #05030B
color8       #909090
color1       #44D244
color9       #44D244
color2       #DECE47
color10      #DECE47
color3       #3377D4
color11      #3377D4
color4       #83558A
color12      #83558A
color5       #D97287
color13      #D97287
color6       #5D9DE6
color14      #5D9DE6
color7       #cfcfce
color15      #cfcfce
